// <auto-generated />
using System;
using GameEvent.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameEvent.Infrastructure.Database.Migrations
{
    [DbContext(typeof(GameEventDbContext))]
    [Migration("20260925084435_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("GameEvent.Infrastructure.Accounts.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLogin")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedLogin")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("GameEvent.Infrastructure.EventLog.GameEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UndoneByEventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.HasIndex("SeasonId", "Sequence")
                        .IsUnique();

                    b.ToTable("GameEvent", (string)null);
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Pool.CategoryRecord", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Pool.GameRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Hours")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.PendingManualEffectRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawEvent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RunId");

                    b.HasIndex("SeasonId", "PlayerId");

                    b.ToTable("PendingManualEffect", (string)null);
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.PlayerGameExclusionRecord", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId", "GameId");

                    b.ToTable("PlayerGameExclusion", (string)null);
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.ProofRecord", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SubmittedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WitnessId")
                        .HasColumnType("TEXT");

                    b.HasKey("RunId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Proof", (string)null);
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.ReviewRecord", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("RunId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.RulesetRecord", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SeasonId", "Version");

                    b.ToTable("Ruleset", (string)null);
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.RunRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AfterFinish")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChallengeDiceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FreeMode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Hours")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoursSource")
                        .HasColumnType("TEXT");

                    b.Property<int>("Moved")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReachedFinish")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RolledAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId", "GameId");

                    b.ToTable("Run", (string)null);
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.SeasonPlayerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CellId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FinishBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FinishOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FinishRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FinishSurplus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Frozen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PointsTick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RerollsThisRoll")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourcesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "Points");

                    b.HasIndex("SeasonId", "UserId")
                        .IsUnique();

                    b.ToTable("SeasonPlayer", (string)null);
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.SeasonRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Deadline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesetJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RulesetVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.SeasonResultRecord", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CellsToFinish")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFirst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Place")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Provisional")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeasonId", "Row");

                    b.HasIndex("PlayerId");

                    b.ToTable("SeasonResult", (string)null);
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.PendingManualEffectRecord", b =>
                {
                    b.HasOne("GameEvent.Infrastructure.Seasons.SeasonPlayerRecord", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEvent.Infrastructure.Seasons.RunRecord", null)
                        .WithMany()
                        .HasForeignKey("RunId");

                    b.HasOne("GameEvent.Infrastructure.Seasons.SeasonRecord", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.PlayerGameExclusionRecord", b =>
                {
                    b.HasOne("GameEvent.Infrastructure.Seasons.SeasonPlayerRecord", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.ProofRecord", b =>
                {
                    b.HasOne("GameEvent.Infrastructure.Seasons.RunRecord", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEvent.Infrastructure.Seasons.SeasonRecord", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.ReviewRecord", b =>
                {
                    b.HasOne("GameEvent.Infrastructure.Seasons.RunRecord", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEvent.Infrastructure.Seasons.SeasonRecord", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.RulesetRecord", b =>
                {
                    b.HasOne("GameEvent.Infrastructure.Seasons.SeasonRecord", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.RunRecord", b =>
                {
                    b.HasOne("GameEvent.Infrastructure.Seasons.SeasonPlayerRecord", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEvent.Infrastructure.Seasons.SeasonRecord", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.SeasonPlayerRecord", b =>
                {
                    b.HasOne("GameEvent.Infrastructure.Seasons.SeasonRecord", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameEvent.Infrastructure.Seasons.SeasonResultRecord", b =>
                {
                    b.HasOne("GameEvent.Infrastructure.Seasons.SeasonPlayerRecord", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEvent.Infrastructure.Seasons.SeasonRecord", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
