/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/antiforgery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AntiforgeryToken"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUser"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUser"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{seasonId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SeasonView"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{seasonId}/roll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RollRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{seasonId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{seasonId}/drop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DropRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{seasonId}/tech-reroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechRerollRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{seasonId}/reroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RerollRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{seasonId}/already-played": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AlreadyPlayedRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{seasonId}/choose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChooseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{seasonId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{seasonId}/runs/{runId}/proof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                    runId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProofRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{seasonId}/runs/{runId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                    runId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentSeasonView"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{seasonId}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RulesView"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seasons/{seasonId}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangeRulesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RulesChangeResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RulesetProblem"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seasons/{seasonId}/pool-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PoolStatsView"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seasons/{seasonId}/players/{playerId}/tech-reroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                    playerId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TechRerollRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seasons/{seasonId}/runs/{runId}/hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                    runId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HoursCorrectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seasons/{seasonId}/runs/{runId}/difficulty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                    runId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DifficultyChangeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seasons/{seasonId}/runs/{runId}/convert-to-drop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                    runId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConvertToDropRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seasons/{seasonId}/proofs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProofQueueItemView"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seasons/{seasonId}/runs/{runId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                    runId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApproveProofRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seasons/{seasonId}/runs/{runId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seasonId: string;
                    runId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RejectProofRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["RejectionProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description «Уже проходил» on the offered game or an option of the pending choice (D-92). */
        AlreadyPlayedRequest: {
            /** Format: uuid */
            commandId: string;
            /** Format: uuid */
            gameId: string;
        };
        AntiforgeryToken: {
            token: string;
            headerName: string;
        };
        /** @description Approve a run: with its proof, or without one («без скрина», a comment then); a lower proven difficulty. */
        ApproveProofRequest: {
            /** Format: uuid */
            commandId: string;
            difficulty?: null | components["schemas"]["Difficulty"];
            comment?: null | string;
        };
        BetRules: {
            /** Format: int32 */
            maxStake: number;
            /** Format: int32 */
            maxOpenBetsPerPlayer: number;
            /** Format: int32 */
            windowHoursAfterRoll: number;
            deadlineOptionsDays: components["schemas"]["EquatableArrayOfint"];
            payoutByHoursPerDay: components["schemas"]["EquatableArrayOfPayoutStep"];
        };
        /** @description How many games of a category can be rolled now; personal exclusions are not subtracted. */
        CategoryStatView: {
            category: string;
            /** Format: int32 */
            weight: number;
            /** Format: int32 */
            available: number;
        };
        /** @enum {unknown} */
        CellType: "start" | "empty" | "finish";
        CellView: {
            id: string;
            type: components["schemas"]["CellType"];
        };
        ChallengeBonus: {
            /** Format: int32 */
            extraDice: number;
        };
        /**
         * @description A new ruleset from the admin's editor: the whole document, the version it was edited from, and a command id
         *     generated once per save.
         */
        ChangeRulesRequest: {
            /** Format: uuid */
            commandId: string;
            /** Format: int32 */
            expectedVersion: number;
            ruleset: components["schemas"]["Ruleset"];
        };
        /**
         * @description What the player is choosing. Stage 1 has games only; branches, targets and outcomes come later (K-5).
         * @enum {unknown}
         */
        ChoiceKind: "game";
        ChoiceOptionView: {
            id: string;
            game: null | components["schemas"]["OfferedGameView"];
        };
        /** @description The pending choice, kept on the server: a reloaded page shows the same options (T2). */
        ChoiceView: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["ChoiceKind"];
            options: components["schemas"]["ChoiceOptionView"][];
        };
        /** @description An answer to the pending choice: its id and the picked option's id. */
        ChooseRequest: {
            /** Format: uuid */
            commandId: string;
            /** Format: uuid */
            choiceId: string;
            optionId: string;
        };
        CoinReward: {
            /** Format: double */
            perHour: number;
            /** Format: int32 */
            min: number;
        };
        CommandResponse: {
            duplicate: boolean;
            events: components["schemas"]["LoggedEventView"][];
        };
        /**
         * @description The player's latest completed run: dice by the hours and the challenge dice apart, each die separately; the total
         *     counts both; the review when there is one; `status` is `rejected` when the admin took the run back.
         */
        CompletedRunView: {
            /** Format: uuid */
            id: string;
            game: components["schemas"]["GameView"];
            difficulty: components["schemas"]["Difficulty"];
            dice: components["schemas"]["DieView"][];
            challengeDice: components["schemas"]["DieView"][];
            /** Format: int32 */
            total: number;
            review: null | components["schemas"]["ReviewView"];
            proof: null | components["schemas"]["ProofView"];
            status: components["schemas"]["RunStatus"];
        };
        /** @description Completing the active run. `estimatedHours` is needed only when the game has no hours. */
        CompleteRequest: {
            /** Format: uuid */
            commandId: string;
            difficulty: components["schemas"]["Difficulty"];
            /** Format: double */
            estimatedHours?: null | number;
            hoursSource?: null | string;
            /** @default false */
            challengeDone: boolean;
            review?: null | components["schemas"]["ReviewInput"];
        };
        /** @description An admin comment on a change to a player's runs; required, the log shows it. */
        ConvertToDropRequest: {
            /** Format: uuid */
            commandId: string;
            comment: null | string;
        };
        /** @enum {unknown} */
        CoopRoundUpFor: "roller";
        CoopRules: {
            /** Format: double */
            pointsShare: number;
            roundUpFor: components["schemas"]["CoopRoundUpFor"];
        };
        /** @description The season the signed-in user sees by default (D-18). */
        CurrentSeasonView: {
            /** Format: uuid */
            id: string;
        };
        CurrentUser: {
            /** Format: uuid */
            id: string;
            login: string;
            name: string;
            role: components["schemas"]["Role"];
            mustChangePassword: boolean;
        };
        DiceCountRule: {
            /** Format: double */
            hoursPerDie: number;
            rounding: components["schemas"]["Rounding"];
            /** Format: int32 */
            min: number;
            /** Format: int32 */
            max: number;
        };
        DieByDifficulty: {
            easy: components["schemas"]["DieRule"];
            normal: components["schemas"]["DieRule"];
            hard: components["schemas"]["DieRule"];
            extreme: components["schemas"]["DieRule"];
        };
        DieRule: {
            /** Format: int32 */
            sides: number;
            grantEvent?: null | components["schemas"]["EventKind"];
        };
        DieView: {
            /** Format: int32 */
            sides: number;
            /** Format: int32 */
            value: number;
        };
        /** @enum {unknown} */
        Difficulty: "easy" | "normal" | "hard" | "extreme";
        /** @description The admin changes the difficulty of a completed run, usually by the proof (Q-5, D-97). */
        DifficultyChangeRequest: {
            /** Format: uuid */
            commandId: string;
            difficulty: null | components["schemas"]["Difficulty"];
            comment: null | string;
        };
        /** @description The drop penalty: `count` dice of `sides`, what they take, and whether a bad event follows. */
        DropPenaltyView: {
            /** Format: int32 */
            count: number;
            /** Format: int32 */
            sides: number;
            affectsPoints: boolean;
            affectsPosition: boolean;
            badEvent: boolean;
        };
        /** @description Drop the active run with the penalty (D-09, D-94). */
        DropRequest: {
            /** Format: uuid */
            commandId: string;
        };
        DropRules: {
            penaltyDice: components["schemas"]["PenaltyDice"];
            affectsPoints: boolean;
            affectsPosition: boolean;
            mandatoryEvent: components["schemas"]["MandatoryEvent"];
        };
        EconomyRules: {
            allowNegativeCoins: boolean;
            /** Format: int32 */
            inventoryLimit: number;
            rarityWeights: components["schemas"]["RarityWeights"];
            shop: components["schemas"]["ShopRules"];
        };
        EffectRules: {
            /** Format: int32 */
            maxChainDepth: number;
            /** Format: int32 */
            maxEventsPerCommand: number;
            hostileCap: components["schemas"]["HostileCap"];
            attacksOnlyOnHigherPoints: boolean;
        };
        /** @enum {unknown} */
        EmptyPoolFallback: "dropZoneFilter";
        /**
         * @description Immutable list with value equality, so records holding lists (events, snapshots) compare by content.
         *     Serialized as a plain JSON array.
         */
        EquatableArrayOfAutoNomination: unknown;
        /**
         * @description Immutable list with value equality, so records holding lists (events, snapshots) compare by content.
         *     Serialized as a plain JSON array.
         */
        EquatableArrayOfint: unknown;
        /**
         * @description Immutable list with value equality, so records holding lists (events, snapshots) compare by content.
         *     Serialized as a plain JSON array.
         */
        EquatableArrayOfLengthFilterStep: unknown;
        /**
         * @description Immutable list with value equality, so records holding lists (events, snapshots) compare by content.
         *     Serialized as a plain JSON array.
         */
        EquatableArrayOfPayoutStep: unknown;
        /**
         * @description Immutable list with value equality, so records holding lists (events, snapshots) compare by content.
         *     Serialized as a plain JSON array.
         */
        EquatableArrayOfShopPriceReset: unknown;
        /**
         * @description Immutable list with value equality, so records holding lists (events, snapshots) compare by content.
         *     Serialized as a plain JSON array.
         */
        EquatableArrayOfstring: unknown;
        /**
         * @description Immutable list with value equality, so records holding lists (events, snapshots) compare by content.
         *     Serialized as a plain JSON array.
         */
        EquatableArrayOfTiebreaker: unknown;
        /**
         * @description Immutable list with value equality, so records holding lists (events, snapshots) compare by content.
         *     Serialized as a plain JSON array.
         */
        EquatableArrayOfVotedNomination: unknown;
        /** @enum {unknown} */
        EventKind: "good" | "bad";
        /** @description Feature flags: a disabled mechanic is invisible in the interface and refused by the engine. */
        Features: {
            mapMode: components["schemas"]["MapMode"];
            shop: boolean;
            items: boolean;
            events: boolean;
            bets: boolean;
            polls: boolean;
            achievements: boolean;
            weeklyChallenge: boolean;
            partnerBoard: boolean;
            reactions: boolean;
            comments: boolean;
            gallery: boolean;
            /**
             * @description Claiming a game's challenge on completion (D-96). Off until games carry a challenge note and the proof checks it;
             *     optional, so older configs without it still read.
             */
            challenges?: boolean;
        };
        FinishRules: {
            requireApprovalForFirst: boolean;
            bonusByOrder: components["schemas"]["EquatableArrayOfint"];
            /** Format: int32 */
            bonusAfterList: number;
        };
        /** @enum {unknown} */
        GameMarkKind: "dropped" | "techRerolled";
        /** @description Another player gave the game up this season: dropped or tech-rerolled it; the game is free again. */
        GameMarkView: {
            playerName: string;
            kind: components["schemas"]["GameMarkKind"];
        };
        GameView: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: double */
            hours: null | number;
        };
        HostileCap: {
            enabled: boolean;
            /** Format: int32 */
            maxActive: number;
        };
        /** @description The admin corrects the hours of a completed run (D-97). */
        HoursCorrectionRequest: {
            /** Format: uuid */
            commandId: string;
            /** Format: double */
            hours: null | number;
            comment: null | string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        InteractionRules: {
            /** Format: int32 */
            inviteTtlHours: number;
        };
        LastDaysLengthFilter: {
            enabled: boolean;
            steps: components["schemas"]["EquatableArrayOfLengthFilterStep"];
        };
        LoggedEventView: {
            /** Format: int64 */
            sequence: number;
            type: string;
        };
        LoginRequest: {
            login: string;
            password: string;
        };
        /** @enum {unknown} */
        MandatoryEvent: "bad" | "none";
        /**
         * @description What created a manual effect; C11 adds item, cell and event sources.
         * @enum {unknown}
         */
        ManualEffectSource: "paidReroll" | "drop" | "difficulty";
        /** @description A manual effect the player still has to play out (D-10, D-93); resolving it comes with C11. */
        ManualEffectView: {
            /** Format: uuid */
            id: string;
            drawEvent: components["schemas"]["EventKind"];
            source: components["schemas"]["ManualEffectSource"];
        };
        /** @enum {unknown} */
        MapMode: "linear" | "graph";
        MapRules: {
            /** Format: int32 */
            linearLength: number;
        };
        /**
         * @description The signed-in player's own turn. While playing: `dropHintMinutes` is `roll.minPlayMinutesBeforeDrop` until
         *     that much has been played by the server clock (only a hint: D-09), then null; `dropPenalty` is what a drop costs
         *     under the rules in force; `techRerollOpen` says whether the player may still tech-reroll themselves (D-94);
         *     `challengesEnabled` says whether a challenge may be claimed on completion (`features.challenges`, D-96).
         */
        MyTurnView: {
            /** Format: uuid */
            playerId: string;
            phase: components["schemas"]["TurnPhase"];
            offer: null | components["schemas"]["OfferedGameView"];
            choice: null | components["schemas"]["ChoiceView"];
            nextReroll: null | components["schemas"]["RerollPriceView"];
            activeRun: null | components["schemas"]["RunView"];
            lastCompleted: null | components["schemas"]["CompletedRunView"];
            manualEffects: components["schemas"]["ManualEffectView"][];
            /** Format: int32 */
            dropHintMinutes: null | number;
            dropPenalty: null | components["schemas"]["DropPenaltyView"];
            techRerollOpen: boolean;
            challengesEnabled: boolean;
        };
        NominationRules: {
            auto: components["schemas"]["EquatableArrayOfAutoNomination"];
            voted: components["schemas"]["EquatableArrayOfVotedNomination"];
        };
        /** @description A game offered to the player, with the hours fixed at roll time and marks from other players (SPEC «Статусы игры»). */
        OfferedGameView: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: double */
            hours: null | number;
            marks: components["schemas"]["GameMarkView"][];
        };
        PenaltyDice: {
            /** Format: int32 */
            count: number;
            /** Format: int32 */
            sides: number;
        };
        PlayerView: {
            /** Format: uuid */
            id: string;
            name: string;
            cellId: string;
            /** Format: int32 */
            points: number;
            phase: components["schemas"]["TurnPhase"];
        };
        /** @description A player whose next roll would find no game: the empty-pool signal. */
        PlayerWithoutGamesView: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        /** @description Pool health of a season for the admin (G10, G11, D-92). */
        PoolStatsView: {
            categories: components["schemas"]["CategoryStatView"][];
            playersWithoutGames: components["schemas"]["PlayerWithoutGamesView"][];
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        /**
         * @description A run to check, in queue order (D-98): finishes on top, then by completion time; with the claimed difficulty, the
         *     counted hours and the dice total, what an approval at a lower difficulty or a reject changes.
         */
        ProofQueueItemView: {
            /** Format: uuid */
            runId: string;
            /** Format: uuid */
            playerId: string;
            playerName: string;
            gameTitle: string;
            /** Format: date-time */
            completedAt: null | string;
            reachedFinish: boolean;
            status: null | components["schemas"]["ProofStatus"];
            links: string[];
            note: null | string;
            witnessName: null | string;
            difficulty: null | components["schemas"]["Difficulty"];
            /** Format: double */
            hours: null | number;
            /** Format: int32 */
            diceTotal: number;
        };
        /** @description The proof of the player's own completed run: links (http/https), a note, or a witness (D-98). */
        ProofRequest: {
            /** Format: uuid */
            commandId: string;
            links: null | string[];
            note?: null | string;
            /** Format: uuid */
            witnessId?: null | string;
        };
        /**
         * @description Where a run's proof stands (SPEC «Очередь пруфов»).
         * @enum {unknown}
         */
        ProofStatus: "pending" | "approved" | "rejected";
        /** @description The proof of a run and how the admin checked it. */
        ProofView: {
            status: components["schemas"]["ProofStatus"];
            links: string[];
            note: null | string;
            comment: null | string;
        };
        RankingRules: {
            tiebreakers: components["schemas"]["EquatableArrayOfTiebreaker"];
        };
        RarityWeights: {
            /** Format: int32 */
            common: number;
            /** Format: int32 */
            epic: number;
            /** Format: int32 */
            legendary: number;
        };
        /** @description A game rule refused the action; `code` is stable and maps to a text in the interface dictionary. */
        RejectionProblem: {
            title: string;
            /** Format: int32 */
            status: number;
            detail: null | string;
            code: string;
        };
        /** @description Reject a run: its points, cells and coins are taken back (D-15, D-98). */
        RejectProofRequest: {
            /** Format: uuid */
            commandId: string;
            comment: null | string;
        };
        /** @description Price of a paid reroll: int? RerollCost.Amount coins, or a bad event (then no amount). */
        RerollCost: {
            kind: components["schemas"]["RerollCostKind"];
            /** Format: int32 */
            amount?: null | number;
        };
        /** @enum {unknown} */
        RerollCostKind: "coins" | "badEvent";
        /**
         * @description How a reroll was paid for.
         * @enum {unknown}
         */
        RerollPayment: "freeThisRoll" | "freeRerollResource" | "coins" | "badEvent";
        /** @description What the next reroll costs, computed by the engine's rule (D-93); only while a game is offered. */
        RerollPriceView: {
            payment: components["schemas"]["RerollPayment"];
            /** Format: int32 */
            coins: number;
        };
        /** @description A reroll of the offered game or the whole pending choice; the price follows D-07. */
        RerollRequest: {
            /** Format: uuid */
            commandId: string;
        };
        /** @description A review: a rating 1–10 and an optional text (D-96). */
        ReviewInput: {
            /** Format: int32 */
            rating: number;
            text?: null | string;
        };
        /** @description A review of the player's own completed run, written later or changed. */
        ReviewRequest: {
            /** Format: uuid */
            commandId: string;
            /** Format: int32 */
            rating: number;
            text?: null | string;
        };
        ReviewView: {
            /** Format: int32 */
            rating: number;
            text: null | string;
        };
        RewardRules: {
            diceCount: components["schemas"]["DiceCountRule"];
            dieByDifficulty: components["schemas"]["DieByDifficulty"];
            challengeBonus: components["schemas"]["ChallengeBonus"];
            unmetConditionPolicy: components["schemas"]["UnmetConditionPolicy"];
            coins: components["schemas"]["CoinReward"];
            coop: components["schemas"]["CoopRules"];
        };
        /**
         * @description Role of an account. An admin who also plays has two accounts (SPEC «Аккаунты»).
         * @enum {unknown}
         */
        Role: "player" | "admin" | "spectator";
        /** @description A game action. `commandId` is generated by the client once per action: a repeat acts once. */
        RollRequest: {
            /** Format: uuid */
            commandId: string;
        };
        RollRules: {
            /** Format: int32 */
            choiceCount: number;
            /** Format: int32 */
            freeRerollsPerRoll: number;
            rerollCost: components["schemas"]["RerollCost"];
            /** Format: int32 */
            techRerollWindowHours: number;
            /** Format: int32 */
            minPlayMinutesBeforeDrop: number;
            emptyPoolFallback: components["schemas"]["EmptyPoolFallback"];
            lastDaysLengthFilter: components["schemas"]["LastDaysLengthFilter"];
        };
        /** @enum {unknown} */
        Rounding: "nearest" | "floor" | "ceil";
        RulesChangeResult: {
            /** Format: int32 */
            version: number;
        };
        Ruleset: {
            /**
             * Format: int32
             * @description Format version of the configuration document (not the season's ruleset version).
             */
            version: number;
            features: components["schemas"]["Features"];
            season: components["schemas"]["SeasonRules"];
            roll: components["schemas"]["RollRules"];
            reward: components["schemas"]["RewardRules"];
            drop: components["schemas"]["DropRules"];
            finish: components["schemas"]["FinishRules"];
            ranking: components["schemas"]["RankingRules"];
            map: components["schemas"]["MapRules"];
            economy: components["schemas"]["EconomyRules"];
            effects: components["schemas"]["EffectRules"];
            interactions: components["schemas"]["InteractionRules"];
            bets: components["schemas"]["BetRules"];
            social: components["schemas"]["SocialRules"];
            nominations: components["schemas"]["NominationRules"];
            weeklyChallenge: components["schemas"]["WeeklyChallengeRules"];
        };
        /**
         * @description One changed value between two versions of the rules: the JSON path (for example `reward.diceCount.max`)
         *     and the values before and after as JSON text (a JSON null is the text `"null"`); null when the field
         *     did not exist on that side.
         */
        RulesetChange: {
            path: string;
            before: null | string;
            after: null | string;
        };
        /** @description A problem in a ruleset: the JSON path of the field and what is wrong, in English for logs. */
        RulesetError: {
            path: string;
            message: string;
        };
        /** @description An invalid ruleset: every problem with the JSON path of its field (C2). */
        RulesetProblem: {
            title: string;
            /** Format: int32 */
            status: number;
            errors: components["schemas"]["RulesetError"][];
        };
        /** @description One version of the rules: when, by whom (null for the season's creation by the system), and what changed. */
        RulesVersionView: {
            /** Format: int32 */
            version: number;
            /** Format: date-time */
            at: string;
            /** Format: uuid */
            authorId: null | string;
            changes: components["schemas"]["RulesetChange"][];
        };
        /** @description The rules in force and their history: who changed what and when (C3). Numbers on the rules page are real. */
        RulesView: {
            /** Format: int32 */
            version: number;
            ruleset: components["schemas"]["Ruleset"];
            history: components["schemas"]["RulesVersionView"][];
        };
        /** @enum {unknown} */
        RunStatus: "playing" | "completed" | "dropped" | "techRerolled" | "rejected";
        RunView: {
            /** Format: uuid */
            id: string;
            game: components["schemas"]["GameView"];
            /** Format: date-time */
            startedAt: string;
        };
        SeasonRules: {
            timezone: string;
            /** Format: int32 */
            maxActiveRunsPerPlayer: number;
            /** Format: int32 */
            inactiveHintDays: number;
        };
        /** @description Sent to everyone watching a season after each committed command: refetch what you show. */
        SeasonUpdate: {
            /** Format: uuid */
            seasonId: string;
            /** Format: int64 */
            fromSequence: number;
            /** Format: int64 */
            toSequence: number;
            types: string[];
        };
        SeasonView: {
            /** Format: uuid */
            id: string;
            cells: components["schemas"]["CellView"][];
            players: components["schemas"]["PlayerView"][];
            me: null | components["schemas"]["MyTurnView"];
            /** Format: int64 */
            lastSequence: number;
        };
        ShopRules: {
            /** Format: int32 */
            lotsPerRoll: number;
            /** Format: int32 */
            lotLifetimeMinutes: number;
            /** Format: int32 */
            rollCost: number;
            /** Format: int32 */
            rerollCostStep: number;
            resetOn: components["schemas"]["EquatableArrayOfShopPriceReset"];
        };
        SocialRules: {
            reactions: components["schemas"]["EquatableArrayOfstring"];
            /** Format: int32 */
            galleryUploadsPerDay: number;
            /** Format: int32 */
            commentsPerDay: number;
            spectatorsCanVote: boolean;
        };
        StartRequest: {
            /** Format: uuid */
            commandId: string;
        };
        /** @enum {unknown} */
        TechRerollReason: "weakPc" | "paidUnavailable" | "doesNotLaunch" | "emulatorTooSlow" | "other" | null;
        /** @description A tech reroll of the active run; `comment` is required for the reason «other» (D-11). */
        TechRerollRequest: {
            /** Format: uuid */
            commandId: string;
            reason: null | components["schemas"]["TechRerollReason"];
            comment?: null | string;
        };
        /**
         * @description Where the player is in the turn cycle. Moving and resolving happen inside one command.
         * @enum {unknown}
         */
        TurnPhase: "idle" | "rolling" | "playing";
        /** @enum {unknown} */
        UnmetConditionPolicy: "noDiceKeepCoins" | "countAsDrop" | "ignore";
        WeeklyChallengeRules: {
            /** Format: int32 */
            defaultRewardCoins: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const cellTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CellType"]> = ["start", "empty", "finish"];
export const choiceKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ChoiceKind"]> = ["game"];
export const coopRoundUpForValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CoopRoundUpFor"]> = ["roller"];
export const difficultyValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Difficulty"]> = ["easy", "normal", "hard", "extreme"];
export const emptyPoolFallbackValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["EmptyPoolFallback"]> = ["dropZoneFilter"];
export const eventKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["EventKind"]> = ["good", "bad"];
export const gameMarkKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["GameMarkKind"]> = ["dropped", "techRerolled"];
export const mandatoryEventValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["MandatoryEvent"]> = ["bad", "none"];
export const manualEffectSourceValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ManualEffectSource"]> = ["paidReroll", "drop", "difficulty"];
export const mapModeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["MapMode"]> = ["linear", "graph"];
export const proofStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ProofStatus"]> = ["pending", "approved", "rejected"];
export const rerollCostKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RerollCostKind"]> = ["coins", "badEvent"];
export const rerollPaymentValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RerollPayment"]> = ["freeThisRoll", "freeRerollResource", "coins", "badEvent"];
export const roleValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Role"]> = ["player", "admin", "spectator"];
export const roundingValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Rounding"]> = ["nearest", "floor", "ceil"];
export const runStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RunStatus"]> = ["playing", "completed", "dropped", "techRerolled", "rejected"];
export const turnPhaseValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TurnPhase"]> = ["idle", "rolling", "playing"];
export const unmetConditionPolicyValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["UnmetConditionPolicy"]> = ["noDiceKeepCoins", "countAsDrop", "ignore"];
export type operations = Record<string, never>;
