using System.Diagnostics;
using System.Threading.Channels;
using GameEvent.Engine.Kernel;

namespace GameEvent.Infrastructure.Queue;

/// <summary>
/// A command addressed to a season, as it travels through the queue. <c>CommandId</c> is generated by the client:
/// a repeated id (double click, retry) is executed once.
/// </summary>
public sealed record CommandEnvelope(Guid CommandId, Guid SeasonId, ICommand Command, Guid? AuthorId);

/// <summary>
/// Result of a command: accepted with its events, rejected, or a duplicate of an earlier command. <see cref="Secret"/>
/// is a temporary password an account command made (D-106): given back once, never stored or repeated.
/// </summary>
public sealed record CommandOutcome(bool IsAccepted, bool IsDuplicate, Rejection? Rejection, IReadOnlyList<LoggedEvent> Events, string? Secret = null);

/// <summary>An event after commit, with its place in the season log.</summary>
public sealed record LoggedEvent(Guid SeasonId, long Sequence, Guid CommandId, IGameEvent Event, DateTimeOffset OccurredAt);

/// <summary>
/// The single entry point for state changes (CLAUDE.md, invariant 2): API, admin and timers enqueue here,
/// one consumer (<see cref="CommandProcessor"/>) executes commands one at a time.
/// </summary>
public sealed class CommandBus
{
    private readonly Channel<Pending> _channel = Channel.CreateUnbounded<Pending>(
        new UnboundedChannelOptions { SingleReader = true, SingleWriter = false });

    internal ChannelReader<Pending> Reader => _channel.Reader;

    private int _queued;

    /// <summary>
    /// Commands waiting for the consumer (the health check, D-107). Counted here: a single-reader channel cannot count
    /// its own items.
    /// </summary>
    public int Queued => Volatile.Read(ref _queued);

    private long _runningSince;

    /// <summary>
    /// How long the consumer has worked on the current command, or null between commands (the health check finds a hung
    /// command, D-107). Monotonic time: a clock change or a test clock does not move it.
    /// </summary>
    public TimeSpan? CurrentCommandRunningFor => Interlocked.Read(ref _runningSince) is var since and not 0
        ? Stopwatch.GetElapsedTime(since)
        : null;

    internal void Taken() => Interlocked.Decrement(ref _queued);

    internal void Running(bool running) => Interlocked.Exchange(ref _runningSince, running ? Stopwatch.GetTimestamp() : 0);

    private volatile bool _consuming;

    /// <summary>The consumer is reading the queue now (the health check, D-107).</summary>
    public bool IsConsuming => _consuming;

    internal void Consuming(bool consuming) => _consuming = consuming;

    public async Task<CommandOutcome> SendAsync(CommandEnvelope envelope, CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(envelope);
        var pending = new Pending(envelope, new TaskCompletionSource<CommandOutcome>(TaskCreationOptions.RunContinuationsAsynchronously));
        Interlocked.Increment(ref _queued);
        try
        {
            await _channel.Writer.WriteAsync(pending, ct);
        }
        catch
        {
            Interlocked.Decrement(ref _queued);
            throw;
        }

        return await pending.Completion.Task.WaitAsync(ct);
    }

    internal void Complete() => _channel.Writer.TryComplete();

    internal sealed record Pending(CommandEnvelope Envelope, TaskCompletionSource<CommandOutcome> Completion);
}

/// <summary>A command of the global log (no season): accounts (D-106) and files (D-108).</summary>
public interface IGlobalCommand : ICommand;

/// <summary>Called after a command's transaction commits (SignalR broadcast in B3).</summary>
public interface ICommittedEventsListener
{
    Task OnCommittedAsync(IReadOnlyList<LoggedEvent> events, CancellationToken ct);
}
