using System.Threading.Channels;
using GameEvent.Engine.Kernel;

namespace GameEvent.Infrastructure.Queue;

/// <summary>
/// A command addressed to a season, as it travels through the queue. <c>CommandId</c> is generated by the client:
/// a repeated id (double click, retry) is executed once.
/// </summary>
public sealed record CommandEnvelope(Guid CommandId, Guid SeasonId, ICommand Command, Guid? AuthorId);

/// <summary>Result of a command: accepted with its events, rejected, or a duplicate of an earlier command.</summary>
public sealed record CommandOutcome(bool IsAccepted, bool IsDuplicate, Rejection? Rejection, IReadOnlyList<LoggedEvent> Events);

/// <summary>An event after commit, with its place in the season log.</summary>
public sealed record LoggedEvent(Guid SeasonId, long Sequence, Guid CommandId, IGameEvent Event, DateTimeOffset OccurredAt);

/// <summary>
/// The single entry point for state changes (CLAUDE.md, invariant 2): API, admin and timers enqueue here,
/// one consumer (<see cref="CommandProcessor"/>) executes commands one at a time.
/// </summary>
public sealed class CommandBus
{
    private readonly Channel<Pending> _channel = Channel.CreateUnbounded<Pending>(
        new UnboundedChannelOptions { SingleReader = true, SingleWriter = false });

    internal ChannelReader<Pending> Reader => _channel.Reader;

    public async Task<CommandOutcome> SendAsync(CommandEnvelope envelope, CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(envelope);
        var pending = new Pending(envelope, new TaskCompletionSource<CommandOutcome>(TaskCreationOptions.RunContinuationsAsynchronously));
        await _channel.Writer.WriteAsync(pending, ct);
        return await pending.Completion.Task.WaitAsync(ct);
    }

    internal void Complete() => _channel.Writer.TryComplete();

    internal sealed record Pending(CommandEnvelope Envelope, TaskCompletionSource<CommandOutcome> Completion);
}

/// <summary>Called after a command's transaction commits (SignalR broadcast in B3).</summary>
public interface ICommittedEventsListener
{
    Task OnCommittedAsync(IReadOnlyList<LoggedEvent> events, CancellationToken ct);
}
