using System.Security.Claims;
using System.Text.Json;
using GameEvent.Engine.Kernel;
using GameEvent.Engine.Map;
using GameEvent.Engine.Rolls;
using GameEvent.Engine.Runs;
using GameEvent.Engine.Seasons;
using GameEvent.Infrastructure.Database;
using GameEvent.Infrastructure.Queue;
using GameEvent.Web.Accounts;
using GameEvent.Web.Hosting;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.EntityFrameworkCore;

namespace GameEvent.Web.Seasons;

/// <summary>A game action. <c>commandId</c> is generated by the client once per action: a repeat acts once.</summary>
public sealed record RollRequest(Guid CommandId);

public sealed record StartRequest(Guid CommandId);

/// <summary>Completing the active run. <c>estimatedHours</c> is needed only when the game has no hours.</summary>
public sealed record CompleteRequest(Guid CommandId, Difficulty Difficulty, decimal? EstimatedHours = null);

public sealed record CommandResponse(bool Duplicate, IReadOnlyList<LoggedEventView> Events);

/// <summary>A game rule refused the action; <c>code</c> is stable and maps to a text in the interface dictionary.</summary>
public sealed record RejectionProblem(string Title, int Status, string? Detail, string Code);

public sealed record LoggedEventView(long Sequence, string Type);

public sealed record SeasonView(Guid Id, IReadOnlyList<CellView> Cells, IReadOnlyList<PlayerView> Players, MyTurnView? Me, long LastSequence);

public sealed record CellView(string Id, CellType Type);

public sealed record PlayerView(Guid Id, string Name, string CellId, int Points, TurnPhase Phase);

public sealed record MyTurnView(Guid PlayerId, TurnPhase Phase, GameView? Offer, RunView? ActiveRun);

public sealed record GameView(Guid Id, string Title, decimal? Hours);

public sealed record RunView(Guid Id, GameView Game, DateTimeOffset StartedAt);

public static class SeasonEndpoints
{
    public const decimal MaxEstimatedHours = 1000;

    public static void MapSeasons(this RouteGroupBuilder api)
    {
        var seasons = api.MapGroup("/seasons/{seasonId:guid}").WithTags("Seasons").RequireAuthorization();

        seasons.MapGet("/", GetSeasonAsync)
            .ProducesProblem(StatusCodes.Status401Unauthorized);

        seasons.MapPost("/roll", (Guid seasonId, RollRequest request, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, CancellationToken ct) =>
            ActAsync(seasonId, request.CommandId, user, db, bus, playerId => new RollGame(playerId), ct))
            .RequireAuthorization(Policies.Player)
            .WithActionErrors();

        seasons.MapPost("/start", (Guid seasonId, StartRequest request, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, CancellationToken ct) =>
            ActAsync(seasonId, request.CommandId, user, db, bus, playerId => new StartRun(playerId), ct))
            .RequireAuthorization(Policies.Player)
            .WithActionErrors();

        seasons.MapPost("/complete", (Guid seasonId, CompleteRequest request, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, CancellationToken ct) =>
            request.EstimatedHours is <= 0 or > MaxEstimatedHours
                ? Task.FromResult<Results<Ok<CommandResponse>, ProblemHttpResult, ValidationProblem, NotFound, ForbidHttpResult>>(
                    TypedResults.ValidationProblem(new Dictionary<string, string[]>
                    {
                        ["estimatedHours"] = [$"Hours must be greater than 0 and at most {MaxEstimatedHours}."],
                    }))
                : ActAsync(seasonId, request.CommandId, user, db, bus, playerId => new CompleteRun(playerId, request.Difficulty, request.EstimatedHours), ct))
            .RequireAuthorization(Policies.Player)
            .WithActionErrors();
    }

    /// <summary>Error answers of a game action, described so the generated client has their types.</summary>
    private static RouteHandlerBuilder WithActionErrors(this RouteHandlerBuilder builder) =>
        builder
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status401Unauthorized)
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status404NotFound)
            .Produces<RejectionProblem>(StatusCodes.Status409Conflict, "application/problem+json");

    private static async Task<Results<Ok<CommandResponse>, ProblemHttpResult, ValidationProblem, NotFound, ForbidHttpResult>> ActAsync(
        Guid seasonId, Guid commandId, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, Func<Guid, ICommand> command, CancellationToken ct)
    {
        if (commandId == Guid.Empty)
        {
            return TypedResults.ValidationProblem(new Dictionary<string, string[]> { ["commandId"] = ["A command id is required."] });
        }

        if (!await db.Seasons.AnyAsync(s => s.Id == seasonId, ct))
        {
            return TypedResults.NotFound();
        }

        // A player acts only for themselves: the player id comes from the signed-in user, never from the request.
        var userId = user.UserId();
        var playerId = await db.SeasonPlayers
            .Where(p => p.SeasonId == seasonId && p.UserId == userId)
            .Select(p => (Guid?)p.Id)
            .SingleOrDefaultAsync(ct);
        if (playerId is null)
        {
            return TypedResults.Forbid();
        }

        var outcome = await bus.SendAsync(new CommandEnvelope(commandId, seasonId, command(playerId.Value), userId), ct);
        if (!outcome.IsAccepted)
        {
            return TypedResults.Problem(
                statusCode: StatusCodes.Status409Conflict,
                title: "The command was rejected.",
                detail: outcome.Rejection!.Detail,
                extensions: new Dictionary<string, object?> { ["code"] = outcome.Rejection.Code });
        }

        return TypedResults.Ok(new CommandResponse(
            outcome.IsDuplicate,
            [.. outcome.Events.Select(e => new LoggedEventView(e.Sequence, EventCatalog.Describe(e.Event.GetType()).Name))]));
    }

    private static async Task<Results<Ok<SeasonView>, NotFound>> GetSeasonAsync(
        Guid seasonId, ClaimsPrincipal user, GameEventDbContext db, CancellationToken ct)
    {
        var created = await db.Events.AsNoTracking()
            .Where(e => e.SeasonId == seasonId && e.Sequence == 1)
            .SingleOrDefaultAsync(ct);
        if (created is null || EventCodec.Decode(new StoredEvent(created.Type, created.Version, created.Data)) is not SeasonCreated season)
        {
            return TypedResults.NotFound();
        }

        // The log position is read first: the data below is at least that fresh, so a client comparing it with
        // hub updates may refetch once too often but never misses one.
        var lastSequence = await db.Events.Where(e => e.SeasonId == seasonId).MaxAsync(e => e.Sequence, ct);
        var players = await db.SeasonPlayers.AsNoTracking().Where(p => p.SeasonId == seasonId).OrderBy(p => p.Name).ToListAsync(ct);

        MyTurnView? me = null;
        var userId = user.UserId();
        if (players.SingleOrDefault(p => p.UserId == userId) is { } mine)
        {
            var offer = mine.OfferJson is null ? null : JsonSerializer.Deserialize<RollOffer>(mine.OfferJson, EngineJson.Options);
            var run = mine.ActiveRunId is { } runId ? await db.Runs.AsNoTracking().SingleAsync(r => r.Id == runId, ct) : null;
            var gameIds = new[] { offer?.GameId, run?.GameId }.OfType<Guid>().ToList();
            var games = await db.Games.AsNoTracking().Where(g => gameIds.Contains(g.Id)).ToDictionaryAsync(g => g.Id, ct);

            me = new MyTurnView(
                mine.Id,
                mine.Phase,
                offer is null ? null : new GameView(offer.GameId, games[offer.GameId].Title, offer.Snapshot.Hours),
                run is null ? null : new RunView(run.Id, new GameView(run.GameId, games[run.GameId].Title, run.Hours ?? games[run.GameId].Hours), run.StartedAt));
        }

        return TypedResults.Ok(new SeasonView(
            seasonId,
            [.. season.Map.Cells.Select(c => new CellView(c.Id, c.Type))],
            [.. players.Select(p => new PlayerView(p.Id, p.Name, p.CellId, p.Points, p.Phase))],
            me,
            lastSequence));
    }
}
