using System.Security.Claims;
using System.Text.Json;
using GameEvent.Engine.Effects;
using GameEvent.Engine.Kernel;
using GameEvent.Engine.Map;
using GameEvent.Engine.Proofs;
using GameEvent.Engine.Ranking;
using GameEvent.Engine.Rolls;
using GameEvent.Engine.Rulesets;
using GameEvent.Engine.Runs;
using GameEvent.Engine.Seasons;
using GameEvent.Engine.Turns;
using GameEvent.Infrastructure.Database;
using GameEvent.Infrastructure.Queue;
using GameEvent.Web.Accounts;
using GameEvent.Web.Hosting;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.EntityFrameworkCore;

using ActionResult = Microsoft.AspNetCore.Http.HttpResults.Results<
    Microsoft.AspNetCore.Http.HttpResults.Ok<GameEvent.Web.Seasons.CommandResponse>,
    Microsoft.AspNetCore.Http.HttpResults.ProblemHttpResult,
    Microsoft.AspNetCore.Http.HttpResults.ValidationProblem,
    Microsoft.AspNetCore.Http.HttpResults.NotFound,
    Microsoft.AspNetCore.Http.HttpResults.ForbidHttpResult>;

namespace GameEvent.Web.Seasons;

/// <summary>A game action. <c>commandId</c> is generated by the client once per action: a repeat acts once.</summary>
public sealed record RollRequest(Guid CommandId);

public sealed record StartRequest(Guid CommandId);

/// <summary>Drop the active run with the penalty (D-09, D-94).</summary>
public sealed record DropRequest(Guid CommandId);

/// <summary>A tech reroll of the active run; <c>comment</c> is required for the reason «other» (D-11).</summary>
public sealed record TechRerollRequest(Guid CommandId, TechRerollReason? Reason, string? Comment = null);

/// <summary>A reroll of the offered game or the whole pending choice; the price follows D-07.</summary>
public sealed record RerollRequest(Guid CommandId);

/// <summary>
/// Resolve a pending manual effect (D-102): <c>outcome</c> «applied» or «notApplicable»; <c>comment</c> is required for
/// «notApplicable» and for the admin, at most 500 characters.
/// </summary>
public sealed record ResolveEffectRequest(Guid CommandId, ManualEffectOutcome? Outcome, string? Comment = null);

/// <summary>«Уже проходил» on the offered game or an option of the pending choice (D-92).</summary>
public sealed record AlreadyPlayedRequest(Guid CommandId, Guid GameId);

/// <summary>An answer to the pending choice: its id and the picked option's id.</summary>
public sealed record ChooseRequest(Guid CommandId, Guid ChoiceId, string OptionId);

/// <summary>Completing the active run. <c>estimatedHours</c> is needed only when the game has no hours.</summary>
public sealed record CompleteRequest(
    Guid CommandId,
    Difficulty Difficulty,
    decimal? EstimatedHours = null,
    string? HoursSource = null,
    bool ChallengeDone = false,
    ReviewInput? Review = null);

/// <summary>A review: a rating 1–10 and an optional text (D-96).</summary>
public sealed record ReviewInput(int Rating, string? Text = null);

/// <summary>The proof of the player's own completed run: links (http/https), a note, or a witness (D-98).</summary>
public sealed record ProofRequest(Guid CommandId, IReadOnlyList<string?>? Links, string? Note = null, Guid? WitnessId = null);

/// <summary>A review of the player's own completed run, written later or changed.</summary>
public sealed record ReviewRequest(Guid CommandId, int Rating, string? Text = null);

public sealed record CommandResponse(bool Duplicate, IReadOnlyList<LoggedEventView> Events);

/// <summary>A game rule refused the action; <c>code</c> is stable and maps to a text in the interface dictionary.</summary>
public sealed record RejectionProblem(string Title, int Status, string? Detail, string Code);

public sealed record LoggedEventView(long Sequence, string Type);

/// <summary>
/// The season screen's data. <c>status</c> and <c>deadline</c> (UTC; the screen shows it in Moscow time) follow the
/// lifecycle (D-101); after the finish <c>leaderboard</c> is the recorded result.
/// </summary>
public sealed record SeasonView(
    Guid Id,
    SeasonStatus Status,
    DateTimeOffset? Deadline,
    IReadOnlyList<CellView> Cells,
    IReadOnlyList<PlayerView> Players,
    IReadOnlyList<LeaderboardRowView> Leaderboard,
    MyTurnView? Me,
    long LastSequence);

/// <summary>
/// A leaderboard row in place order (D-100): tied players share <c>place</c>; <c>isFirst</c> — the first finisher, on top
/// whatever the points, <c>provisional</c> until frozen; <c>cellsToFinish</c> — fewest forward steps to the finish.
/// </summary>
public sealed record LeaderboardRowView(Guid PlayerId, int Place, int Points, int? CellsToFinish, bool IsFirst, bool Provisional);

public sealed record CellView(string Id, CellType Type);

/// <summary>A player on the map and the leaderboard; <c>finishOrder</c> is their order among the finishers, null before the finish.</summary>
public sealed record PlayerView(Guid Id, string Name, string CellId, int Points, TurnPhase Phase, int? FinishOrder);

/// <summary>
/// The signed-in player's own turn. While playing: <c>dropHintMinutes</c> is <c>roll.minPlayMinutesBeforeDrop</c> until
/// that much has been played by the server clock (only a hint: D-09), then null; <c>dropPenalty</c> is what a drop costs
/// under the rules in force; <c>techRerollOpen</c> says whether the player may still tech-reroll themselves (D-94);
/// <c>challengesEnabled</c> says whether a challenge may be claimed on completion (<c>features.challenges</c>, D-96).
/// </summary>
public sealed record MyTurnView(
    Guid PlayerId,
    TurnPhase Phase,
    OfferedGameView? Offer,
    ChoiceView? Choice,
    RerollPriceView? NextReroll,
    RunView? ActiveRun,
    CompletedRunView? LastCompleted,
    IReadOnlyList<ManualEffectView> ManualEffects,
    int? DropHintMinutes,
    DropPenaltyView? DropPenalty,
    bool TechRerollOpen,
    bool ChallengesEnabled,
    MyFinishView? Finish);

/// <summary>The player's own finish (D-99): order among the finishers and whether the first place is final and frozen.</summary>
public sealed record MyFinishView(int Order, bool Frozen);

/// <summary>The drop penalty: <c>count</c> dice of <c>sides</c>, what they take, and whether a bad event follows.</summary>
public sealed record DropPenaltyView(int Count, int Sides, bool AffectsPoints, bool AffectsPosition, bool BadEvent);

/// <summary>A game offered to the player, with the hours fixed at roll time and marks from other players (SPEC «Статусы игры»).</summary>
public sealed record OfferedGameView(Guid Id, string Title, decimal? Hours, IReadOnlyList<GameMarkView> Marks);

/// <summary>Another player gave the game up this season: dropped or tech-rerolled it; the game is free again.</summary>
public sealed record GameMarkView(string PlayerName, GameMarkKind Kind);

public enum GameMarkKind
{
    Dropped,
    TechRerolled,
}

/// <summary>What the next reroll costs, computed by the engine's rule (D-93); only while a game is offered.</summary>
public sealed record RerollPriceView(RerollPayment Payment, int Coins);

/// <summary>A manual effect the player still has to play out (D-10, D-93); the player resolves it (D-102).</summary>
public sealed record ManualEffectView(Guid Id, EventKind DrawEvent, ManualEffectSource Source);

/// <summary>The pending choice, kept on the server: a reloaded page shows the same options (T2).</summary>
public sealed record ChoiceView(Guid Id, ChoiceKind Kind, IReadOnlyList<ChoiceOptionView> Options);

public sealed record ChoiceOptionView(string Id, OfferedGameView? Game);

/// <summary>
/// The player's latest completed run: dice by the hours and the challenge dice apart, each die separately; the total
/// counts both; the review when there is one; <c>status</c> is <c>rejected</c> when the admin took the run back.
/// </summary>
public sealed record CompletedRunView(
    Guid Id,
    GameView Game,
    Difficulty Difficulty,
    IReadOnlyList<DieView> Dice,
    IReadOnlyList<DieView> ChallengeDice,
    int Total,
    ReviewView? Review,
    ProofView? Proof,
    RunStatus Status);

/// <summary>The proof of a run and how the admin checked it.</summary>
public sealed record ProofView(ProofStatus Status, IReadOnlyList<string> Links, string? Note, string? Comment);

public sealed record ReviewView(int Rating, string? Text);

public sealed record DieView(int Sides, int Value);

/// <summary>The season the signed-in user sees by default (D-18).</summary>
public sealed record CurrentSeasonView(Guid Id);

public sealed record GameView(Guid Id, string Title, decimal? Hours);

public sealed record RunView(Guid Id, GameView Game, DateTimeOffset StartedAt);

public static class SeasonEndpoints
{
    /// <summary>The most hours a request may carry: a player's estimate or an admin's correction.</summary>
    public const decimal MaxHours = 1000;

    public const int MaxOptionIdLength = 64;

    public const int MaxCommentLength = Limits.MaxCommentLength;

    public static void MapSeasons(this RouteGroupBuilder api)
    {
        var seasons = api.MapGroup("/seasons/{seasonId:guid}").WithTags("Seasons").RequireAuthorization();

        api.MapGet("/seasons/current", GetCurrentSeasonAsync)
            .WithTags("Seasons")
            .RequireAuthorization()
            .ProducesProblem(StatusCodes.Status401Unauthorized);

        seasons.MapGet("/", GetSeasonAsync)
            .ProducesProblem(StatusCodes.Status401Unauthorized);

        seasons.MapPost("/roll", (Guid seasonId, RollRequest request, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, CancellationToken ct) =>
            ActAsync(seasonId, request.CommandId, user, db, bus, playerId => new RollGame(playerId), ct))
            .RequireAuthorization(Policies.Player)
            .WithActionErrors();

        seasons.MapPost("/start", (Guid seasonId, StartRequest request, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, CancellationToken ct) =>
            ActAsync(seasonId, request.CommandId, user, db, bus, playerId => new StartRun(playerId), ct))
            .RequireAuthorization(Policies.Player)
            .WithActionErrors();

        seasons.MapPost("/drop", (Guid seasonId, DropRequest request, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, CancellationToken ct) =>
            ActAsync(seasonId, request.CommandId, user, db, bus, playerId => new DropRun(playerId), ct))
            .RequireAuthorization(Policies.Player)
            .WithActionErrors();

        seasons.MapPost("/tech-reroll", (Guid seasonId, TechRerollRequest request, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, CancellationToken ct) =>
            TechRerollInvalid(request) is { } invalid
                ? Task.FromResult<ActionResult>(invalid)
                : ActAsync(seasonId, request.CommandId, user, db, bus, playerId => new TechReroll(playerId, request.Reason!.Value, request.Comment), ct))
            .RequireAuthorization(Policies.Player)
            .WithActionErrors();

        seasons.MapPost("/reroll", (Guid seasonId, RerollRequest request, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, CancellationToken ct) =>
            ActAsync(seasonId, request.CommandId, user, db, bus, playerId => new Reroll(playerId), ct))
            .RequireAuthorization(Policies.Player)
            .WithActionErrors();

        seasons.MapPost("/already-played", (Guid seasonId, AlreadyPlayedRequest request, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, CancellationToken ct) =>
            request.GameId == Guid.Empty
                ? Task.FromResult<ActionResult>(
                    TypedResults.ValidationProblem(new Dictionary<string, string[]> { ["gameId"] = ["A game id is required."] }))
                : ActAsync(seasonId, request.CommandId, user, db, bus, playerId => new DeclareAlreadyPlayed(playerId, request.GameId), ct))
            .RequireAuthorization(Policies.Player)
            .WithActionErrors();

        seasons.MapPost("/choose", (Guid seasonId, ChooseRequest request, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, CancellationToken ct) =>
            request.ChoiceId == Guid.Empty || !IsOptionId(request.OptionId)
                ? Task.FromResult<ActionResult>(
                    TypedResults.ValidationProblem(new Dictionary<string, string[]>
                    {
                        ["optionId"] = [$"A choice id and an option id of 1–{MaxOptionIdLength} letters, digits, '-' or '_' are required."],
                    }))
                : ActAsync(seasonId, request.CommandId, user, db, bus, playerId => new MakeChoice(playerId, request.ChoiceId, request.OptionId), ct))
            .RequireAuthorization(Policies.Player)
            .WithActionErrors();

        seasons.MapPost("/complete", (Guid seasonId, CompleteRequest request, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, CancellationToken ct) =>
            CompletionInvalid(request) is { } invalid
                ? Task.FromResult<ActionResult>(invalid)
                : ActAsync(
                    seasonId,
                    request.CommandId,
                    user,
                    db,
                    bus,
                    playerId => new CompleteRun(
                        playerId,
                        request.Difficulty,
                        request.EstimatedHours,
                        request.HoursSource,
                        request.ChallengeDone,
                        request.Review is { } review ? new RunReview(review.Rating, review.Text) : null),
                    ct))
            .RequireAuthorization(Policies.Player)
            .WithActionErrors();

        seasons.MapPost("/runs/{runId:guid}/proof", (Guid seasonId, Guid runId, ProofRequest request, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, CancellationToken ct) =>
            ProofInvalid(request) is { } invalid
                ? Task.FromResult<ActionResult>(invalid)
                : ActAsync(
                    seasonId,
                    request.CommandId,
                    user,
                    db,
                    bus,
                    playerId => new SubmitProof(playerId, runId, [.. request.Links!.OfType<string>()], request.Note, request.WitnessId),
                    ct))
            .RequireAuthorization(Policies.Player)
            .WithActionErrors();

        seasons.MapPost("/runs/{runId:guid}/review", (Guid seasonId, Guid runId, ReviewRequest request, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, CancellationToken ct) =>
            ReviewInvalid(request.Rating, request.Text) is { } invalid
                ? Task.FromResult<ActionResult>(invalid)
                : ActAsync(seasonId, request.CommandId, user, db, bus, playerId => new ReviewRun(playerId, runId, new RunReview(request.Rating, request.Text)), ct))
            .RequireAuthorization(Policies.Player)
            .WithActionErrors();

        // The player resolves only their own effects: the engine checks the owner against the signed-in player (D-102).
        seasons.MapPost("/effects/{effectId:guid}/resolve", (Guid seasonId, Guid effectId, ResolveEffectRequest request, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, CancellationToken ct) =>
            ResolveInvalid(request) is { } invalid
                ? Task.FromResult<ActionResult>(invalid)
                : ActAsync(seasonId, request.CommandId, user, db, bus, playerId => new ResolveManualEffect(effectId, request.Outcome!.Value, request.Comment, playerId), ct))
            .RequireAuthorization(Policies.Player)
            .WithActionErrors();
    }

    /// <summary>A known outcome and a comment within the limit; whether a comment is needed is the engine's rule (409).</summary>
    internal static ValidationProblem? ResolveInvalid(ResolveEffectRequest request) =>
        request.Outcome is not { } outcome || !Enum.IsDefined(outcome)
            ? Invalid("outcome", "«applied» or «notApplicable» is required.")
            : request.Comment?.Length > Limits.MaxCommentLength
                ? Invalid("comment", $"At most {Limits.MaxCommentLength} characters.")
                : null;

    /// <summary>The request-level checks of a completion; the rules (hours needed, source needed) live in the engine.</summary>
    private static ValidationProblem? CompletionInvalid(CompleteRequest request) =>
        request.EstimatedHours is <= 0 or > MaxHours
            ? Invalid("estimatedHours", $"Hours must be greater than 0 and at most {MaxHours}.")
            : request.HoursSource?.Length > Limits.MaxHoursSourceLength
                ? Invalid("hoursSource", $"At most {Limits.MaxHoursSourceLength} characters.")
                : request.Review is { } review
                    ? ReviewInvalid(review.Rating, review.Text)
                    : null;

    private static ValidationProblem? ProofInvalid(ProofRequest request) =>
        request.Links is not { } links || links.Count > Limits.MaxProofLinks || links.Any(link => !ProofLinks.IsValid(link))
            ? Invalid("links", $"Up to {Limits.MaxProofLinks} http or https links of at most {Limits.MaxProofLinkLength} characters.")
            : request.Note?.Length > Limits.MaxCommentLength
                ? Invalid("note", $"At most {Limits.MaxCommentLength} characters.")
                : null;

    private static ValidationProblem? ReviewInvalid(int rating, string? text) =>
        rating is < 1 or > 10
            ? Invalid("rating", "A rating is 1–10.")
            : text?.Length > Limits.MaxReviewLength
                ? Invalid("text", $"At most {Limits.MaxReviewLength} characters.")
                : null;

    private static ValidationProblem Invalid(string field, string message) =>
        TypedResults.ValidationProblem(new Dictionary<string, string[]> { [field] = [message] });

    // Option ids are engine-made (a game id in the N format); anything else never reaches the engine.
    private static bool IsOptionId(string? id) =>
        id is { Length: > 0 and <= MaxOptionIdLength } && id.All(c => char.IsAsciiLetterOrDigit(c) || c is '-' or '_');

    /// <summary>The request-level checks of a tech reroll; the reason's rules live in the engine.</summary>
    internal static ValidationProblem? TechRerollInvalid(TechRerollRequest request) =>
        request.Reason is not { } reason || !Enum.IsDefined(reason)
            ? TypedResults.ValidationProblem(new Dictionary<string, string[]> { ["reason"] = ["A known tech reroll reason is required."] })
            : request.Comment?.Length > MaxCommentLength
                ? TypedResults.ValidationProblem(new Dictionary<string, string[]> { ["comment"] = [$"At most {MaxCommentLength} characters."] })
                : null;

    /// <summary>Error answers of a game action, described so the generated client has their types.</summary>
    internal static RouteHandlerBuilder WithActionErrors(this RouteHandlerBuilder builder) =>
        builder
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status401Unauthorized)
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status404NotFound)
            .Produces<RejectionProblem>(StatusCodes.Status409Conflict, "application/problem+json");

    private static async Task<ActionResult> ActAsync(
        Guid seasonId, Guid commandId, ClaimsPrincipal user, GameEventDbContext db, CommandBus bus, Func<Guid, ICommand> command, CancellationToken ct)
    {
        if (await PrecheckAsync(seasonId, commandId, db, ct) is { } refused)
        {
            return refused;
        }

        // A player acts only for themselves: the player id comes from the signed-in user, never from the request.
        var userId = user.UserId();
        var playerId = await db.SeasonPlayers
            .Where(p => p.SeasonId == seasonId && p.UserId == userId)
            .Select(p => (Guid?)p.Id)
            .SingleOrDefaultAsync(ct);
        if (playerId is null)
        {
            return TypedResults.Forbid();
        }

        return await SendAsync(seasonId, commandId, command(playerId.Value), userId, bus, ct);
    }

    /// <summary>A game or admin action needs a command id and an existing season.</summary>
    internal static async Task<ActionResult?> PrecheckAsync(Guid seasonId, Guid commandId, GameEventDbContext db, CancellationToken ct)
    {
        if (commandId == Guid.Empty)
        {
            return TypedResults.ValidationProblem(new Dictionary<string, string[]> { ["commandId"] = ["A command id is required."] });
        }

        if (!await db.Seasons.AnyAsync(s => s.Id == seasonId, ct))
        {
            return TypedResults.NotFound();
        }

        return null;
    }

    /// <summary>Sends a checked command through the queue: 409 with the engine code on a rejection.</summary>
    internal static async Task<ActionResult> SendAsync(
        Guid seasonId, Guid commandId, ICommand command, Guid? authorId, CommandBus bus, CancellationToken ct)
    {
        var outcome = await bus.SendAsync(new CommandEnvelope(commandId, seasonId, command, authorId), ct);
        if (!outcome.IsAccepted)
        {
            return TypedResults.Problem(
                statusCode: StatusCodes.Status409Conflict,
                title: "The command was rejected.",
                detail: outcome.Rejection!.Detail,
                extensions: new Dictionary<string, object?> { ["code"] = outcome.Rejection.Code });
        }

        return TypedResults.Ok(new CommandResponse(
            outcome.IsDuplicate,
            [.. outcome.Events.Select(e => new LoggedEventView(e.Sequence, EventCatalog.Describe(e.Event.GetType()).Name))]));
    }

    private static async Task<Results<Ok<SeasonView>, NotFound>> GetSeasonAsync(
        Guid seasonId, ClaimsPrincipal user, GameEventDbContext db, IClock clock, CancellationToken ct)
    {
        var created = await db.Events.AsNoTracking()
            .Where(e => e.SeasonId == seasonId && e.Sequence == 1)
            .SingleOrDefaultAsync(ct);
        if (created is null || EventCodec.Decode(new StoredEvent(created.Type, created.Version, created.Data)) is not SeasonCreated season)
        {
            return TypedResults.NotFound();
        }

        // The log position is read first: the data below is at least that fresh, so a client comparing it with
        // hub updates may refetch once too often but never misses one.
        var lastSequence = await db.Events.Where(e => e.SeasonId == seasonId).MaxAsync(e => e.Sequence, ct);
        var players = await db.SeasonPlayers.AsNoTracking().Where(p => p.SeasonId == seasonId).OrderBy(p => p.Name).ToListAsync(ct);
        var seasonRecord = await db.Seasons.AsNoTracking().SingleAsync(s => s.Id == seasonId, ct);
        var rules = JsonSerializer.Deserialize<Ruleset>(seasonRecord.RulesetJson, EngineJson.Options)!;
        var completedRuns = await db.Runs.AsNoTracking()
            .Where(r => r.SeasonId == seasonId && r.Status == RunStatus.Completed)
            .GroupBy(r => r.PlayerId)
            .Select(g => new { g.Key, Count = g.Count() })
            .ToDictionaryAsync(x => x.Key, x => x.Count, ct);
        var result = await db.SeasonResults.AsNoTracking().Where(x => x.SeasonId == seasonId).OrderBy(x => x.Row).ToListAsync(ct);
        var leaderboard = result.Count > 0
            ? [.. result.Select(x => new LeaderboardRow(x.PlayerId, x.Place, x.Points, x.CellsToFinish, x.IsFirst, x.Provisional))]
            : Leaderboard.Rank(
            players.Select(p => new RankingEntry(
                p.Id, p.Points, p.CellId, p.FinishOrder, p.Frozen, completedRuns.GetValueOrDefault(p.Id), p.PointsTick)),
            rules.Ranking,
            season.Map);

        MyTurnView? me = null;
        var userId = user.UserId();
        if (players.SingleOrDefault(p => p.UserId == userId) is { } mine)
        {
            var offer = mine.OfferJson is null ? null : JsonSerializer.Deserialize<RollOffer>(mine.OfferJson, EngineJson.Options);
            var choice = mine.ChoiceJson is null ? null : JsonSerializer.Deserialize<PendingChoice>(mine.ChoiceJson, EngineJson.Options);
            var run = mine.ActiveRunId is { } runId ? await db.Runs.AsNoTracking().SingleAsync(r => r.Id == runId, ct) : null;
            // One active run per player (C4 keeps it that way), so the latest started completed run is the latest
            // completed one. Revisit with a completion time column if several active runs are ever allowed.
            var last = await db.Runs.AsNoTracking()
                .Where(r => r.PlayerId == mine.Id && (r.Status == RunStatus.Completed || r.Status == RunStatus.Rejected))
                .OrderByDescending(r => r.StartedAt)
                .FirstOrDefaultAsync(ct);
            var lastReview = last is null ? null : await db.Reviews.AsNoTracking().SingleOrDefaultAsync(x => x.RunId == last.Id, ct);
            var lastProof = last is null ? null : await db.Proofs.AsNoTracking().SingleOrDefaultAsync(x => x.RunId == last.Id, ct);
            var gameIds = new[] { offer?.GameId, run?.GameId, last?.GameId }
                .Concat(choice?.Options.Select(o => o.Game?.GameId) ?? [])
                .OfType<Guid>()
                .ToList();
            var games = await db.Games.AsNoTracking().Where(g => gameIds.Contains(g.Id)).ToDictionaryAsync(g => g.Id, ct);

            var coupons = JsonSerializer.Deserialize<ResourceBag>(mine.ResourcesJson, EngineJson.Options)[RerollPrice.FreeRerollsResource];
            var effects = await db.ManualEffects.AsNoTracking()
                .Where(x => x.SeasonId == seasonId && x.PlayerId == mine.Id)
                .OrderBy(x => x.Id)
                .Select(x => new ManualEffectView(x.Id, x.DrawEvent, x.Source))
                .ToListAsync(ct);
            var price = mine.Frozen ? (Payment: RerollPayment.FreeMode, Coins: 0) : RerollPrice.Next(mine.RerollsThisRoll, coupons, rules.Roll);
            var now = clock.UtcNow;

            // Other players' drops and tech rerolls of the offered games (SPEC «Статусы игры в сезоне»: a mark).
            var offeredIds = new[] { offer?.GameId }.Concat(choice?.Options.Select(o => o.Game?.GameId) ?? []).OfType<Guid>().ToList();
            var marks = (await db.Runs.AsNoTracking()
                    .Where(r => r.SeasonId == seasonId && r.PlayerId != mine.Id && offeredIds.Contains(r.GameId)
                        && (r.Status == RunStatus.Dropped || r.Status == RunStatus.TechRerolled))
                    .Join(db.SeasonPlayers, r => r.PlayerId, p => p.Id, (r, p) => new { r.GameId, r.Status, r.StartedAt, p.Name })
                    .ToListAsync(ct))
                .OrderBy(x => x.StartedAt)
                .ToLookup(
                    x => x.GameId,
                    x => new GameMarkView(x.Name, x.Status == RunStatus.Dropped ? GameMarkKind.Dropped : GameMarkKind.TechRerolled));
            OfferedGameView Offered(RollOffer o) => new(o.GameId, games[o.GameId].Title, o.Snapshot.Hours, [.. marks[o.GameId]]);

            var playing = mine.Phase == TurnPhase.Playing && run is not null;
            var played = playing ? now - run!.StartedAt : TimeSpan.Zero;
            var snapshot = playing ? JsonSerializer.Deserialize<RunSnapshot>(run!.SnapshotJson, EngineJson.Options)! : null;
            var drop = rules.Drop;

            me = new MyTurnView(
                mine.Id,
                mine.Phase,
                offer is null ? null : Offered(offer),
                choice is null ? null : new ChoiceView(
                    choice.ChoiceId,
                    choice.Kind,
                    [.. choice.Options.Select(o => new ChoiceOptionView(o.Id, o.Game is null ? null : Offered(o.Game)))]),
                mine.Phase == TurnPhase.Rolling ? new RerollPriceView(price.Payment, price.Coins) : null,
                run is null ? null : new RunView(run.Id, Game(run, games[run.GameId]), run.StartedAt),
                last is null ? null : Completed(last, games[last.GameId], lastReview, lastProof),
                effects,
                playing && played < TimeSpan.FromMinutes(rules.Roll.MinPlayMinutesBeforeDrop) ? rules.Roll.MinPlayMinutesBeforeDrop : null,
                // The frozen first drops with no penalty; a finisher's position is fixed (D-99).
                playing && !mine.Frozen
                    ? new DropPenaltyView(
                        drop.PenaltyDice.Count,
                        drop.PenaltyDice.Sides,
                        drop.AffectsPoints,
                        drop.AffectsPosition && mine.FinishOrder is null,
                        drop.MandatoryEvent == MandatoryEvent.Bad)
                    : null,
                playing && now - run!.RolledAt <= TimeSpan.FromHours(snapshot!.TechRerollWindowHours),
                rules.Features.Challenges,
                mine.FinishOrder is { } order ? new MyFinishView(order, mine.Frozen) : null);
        }

        return TypedResults.Ok(new SeasonView(
            seasonId,
            seasonRecord.Status,
            seasonRecord.Deadline,
            [.. season.Map.Cells.Select(c => new CellView(c.Id, c.Type))],
            [.. players.Select(p => new PlayerView(p.Id, p.Name, p.CellId, p.Points, p.Phase, p.FinishOrder))],
            [.. leaderboard.Select(r => new LeaderboardRowView(r.PlayerId, r.Place, r.Points, r.CellsToFinish, r.IsFirst, r.Provisional))],
            me,
            lastSequence));
    }

    /// <summary>A run's game: the run's own hours when known, otherwise the pool's.</summary>
    private static GameView Game(Infrastructure.Seasons.RunRecord run, Infrastructure.Pool.GameRecord game) =>
        new(run.GameId, game.Title, run.Hours ?? game.Hours);

    private static CompletedRunView Completed(
        Infrastructure.Seasons.RunRecord run,
        Infrastructure.Pool.GameRecord game,
        Infrastructure.Seasons.ReviewRecord? review,
        Infrastructure.Seasons.ProofRecord? proof)
    {
        var dice = JsonSerializer.Deserialize<EquatableArray<Die>>(run.DiceJson, EngineJson.Options);
        var challenge = JsonSerializer.Deserialize<EquatableArray<Die>>(run.ChallengeDiceJson, EngineJson.Options);
        return new CompletedRunView(
            run.Id,
            Game(run, game),
            run.Difficulty ?? throw new InvalidOperationException($"Completed run {run.Id} has no difficulty."),
            [.. dice.Select(d => new DieView(d.Sides, d.Value))],
            [.. challenge.Select(d => new DieView(d.Sides, d.Value))],
            dice.Sum(d => d.Value) + challenge.Sum(d => d.Value),
            review is null ? null : new ReviewView(review.Rating, review.Text),
            proof is null
                ? null
                : new ProofView(
                    proof.Status,
                    JsonSerializer.Deserialize<EquatableArray<string>>(proof.LinksJson, EngineJson.Options).ToArray(),
                    proof.Note,
                    proof.Comment),
            run.Status);
    }

    /// <summary>The latest season the user plays in; for spectators and admins, the latest season.</summary>
    private static async Task<Results<Ok<CurrentSeasonView>, NotFound>> GetCurrentSeasonAsync(
        ClaimsPrincipal user, GameEventDbContext db, CancellationToken ct)
    {
        var userId = user.UserId();
        var mine = await db.SeasonPlayers.AsNoTracking()
            .Where(p => p.UserId == userId)
            .Join(db.Seasons, p => p.SeasonId, s => s.Id, (_, s) => s)
            .OrderByDescending(s => s.CreatedAt)
            .Select(s => (Guid?)s.Id)
            .FirstOrDefaultAsync(ct);
        var id = mine ?? await db.Seasons.AsNoTracking().OrderByDescending(s => s.CreatedAt).Select(s => (Guid?)s.Id).FirstOrDefaultAsync(ct);
        return id is null ? TypedResults.NotFound() : TypedResults.Ok(new CurrentSeasonView(id.Value));
    }
}
