<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FsCheck" />
    <PackageReference Include="FsCheck.Xunit.v3" />
    <PackageReference Include="JsonSchema.Net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameEvent.Engine\GameEvent.Engine.csproj" />
  </ItemGroup>

</Project>
